####################################################################################################################################################  
#  																																				   #
# This file has been generated by Amit Patankar:  																								   #
#     Created by              : amit.patankar																									   #	
#     Created on              : 27-06-2013																										   #
#     Directory               : /Desktop/																								           #
#     Purpose		    	  : This structure holds the attributes of each questions.							   							   	   #
#  													   																							   #
#################################################################################################################################################### 

from Values import *

#Question Class
class Question(object):

	#This is the default constructor with all variables defined.
	def __init__(self, section, number, answer, difficulty, range_r, question_type):
		self.section = section
		self.number = number
		self.answer = answer
		self.difficulty = difficulty
		self.range = range_r
		self.type = question_type

	#MAKE A CONSTRUCTOR THAT CONSTRUCTS OUT OF ARRAY

	#This is the default constructor with all variables defined.
	def __init__(self, section, array):
		if len(array) != PARSED_ARRAY_SIZE:
			print ("Error: Invalid line in CSV")
			print (array)
			return

		self.section = section
		self.number = int(array[NUMBER_INDEX])
		self.answer = array[ANSWER_INDEX]
		self.difficulty = int(array[DIFFICULTY_INDEX])
		self.range = array[RANGE_INDEX]
		self.type = array[TYPE_INDEX]

	def get_id(self):
		return self.section.get_id() + FIELD_SEP + str(self.number)



