####################################################################################################################################################  
#  																																				   #
# This file has been generated by Amit Patankar:  																								   #
#     Created by              : amit.patankar																									   #	
#     Created on              : 17-07-2013																										   #
#     Directory               : /Desktop/																								           #
#     Purpose		    	  : This structure is a question that has been scored.						   							   	   	   #
#  													   																							   #
####################################################################################################################################################


#Base Scored Question Class
class Scored_Question(object):

	#This is the default constructor with all variables defined.
	def __init__(self, section, ca, ia, difficulty, question_type):
		self.scored_section = scored_section
		self.correct_answer = ca
		self.incorrect_answer = ia
		self.difficulty = difficulty
		self.question_type = question_type

	def __init__(self, array):
		if len(array) != GRADED_ARRAY_SIZE:
			print ("Error: Invalid line in CSV")
			print (array)
			return
		self.section_id = array[SECTION_ID_INDEX]
		self.correct_answer = array[CA_INDEX]
		self.incorrect_answer = array[IA_INDEX]
		self.difficulty = array[DIFF_INDEX]
		self.question_type = array[QTYPE_INDEX]

	def get_id(self):
		return scored_section.get_id() + FIELD_SEP + str(num)



	