####################################################################################################################################################  
#  																																				   #
# This file has been generated by Amit Patankar:  																								   #
#     Created by              : amit.patankar																									   #	
#     Created on              : 17-07-2013																										   #
#     Directory               : /Desktop/																								           #
#     Purpose		    	  : This structure is a section that has been scored.							   							   	   	   #
#  													   																							   #
#################################################################################################################################################### 


#Base Scored Section Class
class Scored_Section(object):

	#This is the default constructor with all variables defined.
	def __init__(self, scored_test, section_type, score):
		self.scored_test = scored_test
		self.type = section_type
		self.question_summary = None
		self.score = score
		self.missed_questions = []

	def add_miss(self, scored_question):
		self.missed_questions.append(scored_question)

	def add_summary(self, qa, qm, qb):
		self.question_summary = Question_Summary(qa, qm, qb)

	def get_ID(self):
		return self.scored_test.get_id() + FIELD_SEP + str(self.section_number)
