####################################################################################################################################################  
#  																																				   #
# This file has been generated by Amit Patankar:  																								   #
#     Created by              : amit.patankar																									   #	
#     Created on              : 11-07-2013																										   #
#     Directory               : /Desktop/																								           #
#     Purpose		    	  : This structure holds the attributes of each section.							   							   	   #
#  													   																							   #
#################################################################################################################################################### 

from Values import *
from Question import *
import csv
#Base Section Class
class Section(object):

	#This is the default constructor with all variables defined.
	def __init__(self, test, index, section_type):
		self.test = test
		self.section_number = index
		self.type = section_type
		self.questions = {}
		self.is_trial = False

	def add_question(self, question):
		self.questions[question.number] = question

	#This selects the correct section.
	def parse_questions(self, filename):
		with open(filename, 'rU') as f:
		    reader = csv.reader(f)
		    for row in reader:
		    	if row != LABEL_VECTOR:
		        	q = Question(self, row)
		        	self.add_question(q)

	def get_question(self, index):
		if (index <= 0 or index >= self.size):
			print ("Error: Not a valid question number")
			return
		return self.questions[index]

	def get_id(self):
		return self.test.get_id() + FIELD_SEP + str(self.section_number)


	def size(self):
		return len(self.questions)

#Trial Section Class for CollegeBoard Experimentals
class Trial_Section(Section):

	#This is the default constructor with all variables defined.
	def __init__(self, test, index):
		self.test = test
		self.section_number = index
		self.is_trial = True
		self.type = TRIAL_TYPE
		self.questions = {}

#Trial Essay Section Always #1
class Essay_Section(Section):

	#This is the default constructor with all variables defined.
	def __init__(self, test):
		self.test = test
		self.section_number = ESSAY_SECTION_INDEX
		self.type = ESSAY_TYPE
		self.is_trial = False
		self.questions = {}








