        #calculate differences if more than one test taken
        if len(self.tests_taken) >= 2:
            index = 1.5
            index1 = 0
            index2 = 1
            while (index2 < len(self.tests_taken)):
                s2.append([index, s1[index2][1] - s1[index1][1]])
                index1 += 1
                index2 += 1
                index += 1


        lines.append('<div id="chart1" style="width:561px; height:400px"></div>')
        lines.append(' <script class="code" type="text/javascript">')
        lines.append('$(document).ready(function () {')
        lines.append('var s1 = ' + str(s1) + ';')
        lines.append('var s2 = ' + str(s2) + ';')
        lines.append('plot1 = $.jqplot("chart1", [s2, s1], {')
        lines.append('animate: true,')
        lines.append('animateReplot: true,')
        lines.append('cursor: {')
        lines.append('show: true,')
        lines.append('zoom: true,')
        lines.append('looseZoom: true,')
        lines.append('showTooltip: false')
        lines.append('},')
        lines.append('series:[')
        lines.append('{')
        lines.append('pointLabels: {')
        lines.append('show: true')
        lines.append('},')
        lines.append('renderer: $.jqplot.BarRenderer,')
        lines.append('showHighlight: false,')
        lines.append("yaxis: 'y2axis',")
        lines.append('rendererOptions: {')
        lines.append('animation: {')
        lines.append('speed: 2500')
        lines.append('},')
        lines.append('barWidth: 15,')
        lines.append('barPadding: -15,')
        lines.append('barMargin: 0,')
        lines.append('highlightMouseOver: false')
        lines.append('}')
        lines.append('},')
        lines.append('{')
        lines.append('rendererOptions: {')
        lines.append('animation: {')
        lines.append('speed: 2000')
        lines.append('}')
        lines.append('}')
        lines.append('}')
        lines.append('],')
        lines.append('axesDefaults: {')
        lines.append('pad: 0')
        lines.append('},')
        lines.append('axes: {')
        lines.append('xaxis: {')
        lines.append('tickInterval: 1,')
        lines.append('drawMajorGridlines: false,')
        lines.append('drawMinorGridlines: true,')
        lines.append('drawMajorTickMarks: false,')
        lines.append('rendererOptions: {')
        lines.append('tickInset: 0.5,')
        lines.append('minorTicks: 1')
        lines.append('}')
        lines.append('},')
        lines.append('yaxis: {')
        lines.append('tickOptions: {')
        lines.append('formatString: "' + "$%" + "'" + 'd"')
        lines.append('},')
        lines.append('rendererOptions: {')
        lines.append('forceTickAt0: true')
        lines.append('}')
        lines.append('},')
        lines.append('y2axis: {')
        lines.append('tickOptions: {')
        lines.append('formatString: "' + "$%" + "'" + 'd"')
        lines.append('},')
        lines.append('rendererOptions: {')
        lines.append('alignTicks: true,')
        lines.append('forceTickAt0: true')
        lines.append('}')
        lines.append('}')
        lines.append('},')
        lines.append('highlighter: {')
        lines.append('show: true, ')
        lines.append('showLabel: true,')
        lines.append("tooltipAxes: 'y',")
        lines.append("sizeAdjust: 7.5 , tooltipLocation : 'ne'")
        lines.append('}')
        lines.append('});')
        lines.append('});')
        lines.append('</script>')